### ISSUE TITLE
move flake8 from tox to pre-commit

### ISSUE THREAD

**Issue by jugmac00** [jugmac00/hibpcli#44]
... and run pre-commit via tox.

**Comment by HarryET** [comment]
Hey! i'm working on it now, i'll put a pr in when/if its done :)

**Comment by jugmac00** [comment]
This is awesome! Tell me if you need any help.

**Comment by HarryET** [comment]
not sure how to test it so you might have to xD

**Comment by jugmac00** [comment]
Well, you could cause a temporary flake8 violation, ie too many blank lines between two methods, and then run flake8 via pre-commit via tox and it should complain.

Are you familiar with these three tools and how they interact?

**Comment by HarryET** [comment]
no sadly, i thought it might be an easy first pr to move over some configs?

**Comment by HarryET** [comment]
here is my fork with the changes i made so far https://github.com/HarryET/hibpcli

**Comment by jugmac00** [comment]
Please create a pull request - so I can see the diff.

There should be a green button on your repo for that.

**Comment by HarryET** [comment]
yup, i will do that

**Comment by HarryET** [comment]
https://github.com/jugmac00/hibpcli/pull/47

**Comment by jugmac00** [comment]
I have dinner now - I'll be back in some and then we can discuss how to proceed.

I created two short videos about those tools to give support for a similar issue:
https://www.youtube.com/watch?v=0405xzlycD8

**Comment by HarryET** [comment]
whatching the videos now and might make a new pr for when your back!

**Comment by HarryET** [comment]
ok pr is updated now https://github.com/jugmac00/hibpcli/pull/47

**Comment by jugmac00** [comment]
I will directly comment in the pull request.

**Comment by HarryET** [comment]
perfect!

**Comment by jugmac00** [comment]
Closed by #47

Thanks a lot! And happy Hacktoberfest!
