### ISSUE TITLE
Change the message if no leak found

### ISSUE THREAD

**Issue by eumiro** [jugmac00/hibpcli#58]
The wording of messages _“Hooray, everything is safe!”_ and _“Your password is safe!”_ implies these passwords are safe. Actually they only have not been reported as unsafe _until now_.

How about: _“Your password is probably safe.”_ or _“This password has not been reported unsafe until now.”_ or let's find a better message in the discussion.

**Comment by jugmac00** [comment]
I like your second suggestion. Would you kindly create a pull request?
